name: wax
version: 0.1.0.0
synopsis: Functional WS by MC Ștefan
description: Functional WS by MC Ștefan
author: Boris Buliga <boris@d12frosted.io>
maintainer: Boris Buliga <boris@d12frosted.io>
license: MIT
github: d12frosted/wax
category: Development

ghc-options: -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints

dependencies:
  - base >= 4.9 && < 5
  - criterion
  - deepseq
  - hashable
  - lens
  - parallel
  - path
  - path-io
  - random
  - rio
  - time
  - unordered-containers

executables:
  wax-fib-profile:
    source-dirs: fibonacci
    main: Wax.Criterion

  wax-mapreduce-profile:
    source-dirs: mapreduce
    main: Wax.Criterion

  wax-logging:
    source-dirs: logging
    main: Wax.Logging

  wax-parser:
    source-dirs: parser
    main: Wax.Parser
